services:
  postgres:
    image: postgres:16
    container_name: ttrx-postgres
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  indexer:
    build: ./indexer
    container_name: ttrx-indexer
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
  
  backend:
    build: ./backend
    container_name: ttrx-backend
    env_file: 
      - .env
    ports:
      - "${BACKEND_ACCESS_PORT}:${BACKEND_INTERNAL_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_CONTRACT_ADDRESS=${VITE_CONTRACT_ADDRESS}
    container_name: ttrx-frontend
    env_file: .env
    ports:
      - "${FRONTEND_ACCESS_PORT}:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0

volumes:
  pgdata:
